CREATE TABLE IF NOT EXISTS stores (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, code VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL,
 contact VARCHAR(100) NOT NULL DEFAULT '', phone VARCHAR(40) NOT NULL DEFAULT '', address VARCHAR(300) NOT NULL DEFAULT '',
 active BOOLEAN NOT NULL DEFAULT TRUE, version INT NOT NULL DEFAULT 0
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS users (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(60) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 name VARCHAR(100) NOT NULL, role VARCHAR(20) NOT NULL, store_id BIGINT NULL, phone VARCHAR(40) NOT NULL DEFAULT '',
 active BOOLEAN NOT NULL DEFAULT TRUE, auth_version INT NOT NULL DEFAULT 0, failed_count INT NOT NULL DEFAULT 0,
 locked_until TIMESTAMP NULL, version INT NOT NULL DEFAULT 0,
 FOREIGN KEY (store_id) REFERENCES stores(id),
 CONSTRAINT ck_user_role CHECK ((role IN ('SUPER','ADMIN') AND store_id IS NULL) OR (role IN ('STORE_ORDER','STORE_VIEW') AND store_id IS NOT NULL))
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS categories (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(60) NOT NULL UNIQUE,
 sort_order INT NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE,
 version INT NOT NULL DEFAULT 0, CHECK(sort_order >= 0)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS products (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, code VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL,
 category VARCHAR(60) NOT NULL, category_id BIGINT NOT NULL, unit VARCHAR(100) NOT NULL, price DECIMAL(14,2) NOT NULL,
 stock INT NOT NULL DEFAULT 0, safety_stock INT NOT NULL DEFAULT 30, active BOOLEAN NOT NULL DEFAULT TRUE,
 description TEXT NOT NULL, version INT NOT NULL DEFAULT 0,
 CONSTRAINT fk_products_category FOREIGN KEY(category_id) REFERENCES categories(id),
 CHECK (price >= 0 AND stock >= 0 AND safety_stock >= 0)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS product_images (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, product_id BIGINT NOT NULL, mime VARCHAR(40) NOT NULL,
 content MEDIUMBLOB NOT NULL, sort_no INT NOT NULL, FOREIGN KEY(product_id) REFERENCES products(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS store_prices (
 store_id BIGINT NOT NULL, product_id BIGINT NOT NULL, price DECIMAL(14,2) NOT NULL,
 PRIMARY KEY(store_id,product_id), FOREIGN KEY(store_id) REFERENCES stores(id), FOREIGN KEY(product_id) REFERENCES products(id), CHECK(price >= 0)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS purchase_orders (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, created_by BIGINT NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, status VARCHAR(20) NOT NULL DEFAULT '접수',
 note VARCHAR(1000) NOT NULL DEFAULT '', cancel_reason VARCHAR(1000) NULL, cancelled_at TIMESTAMP NULL,
 FOREIGN KEY(store_id) REFERENCES stores(id), FOREIGN KEY(created_by) REFERENCES users(id), INDEX idx_order_store(store_id,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS order_lines (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, order_id BIGINT NOT NULL, line_no INT NOT NULL, product_id BIGINT NOT NULL,
 product_name VARCHAR(100) NOT NULL, unit VARCHAR(100) NOT NULL, unit_price DECIMAL(14,2) NOT NULL,
 quantity INT NOT NULL, shipped INT NOT NULL DEFAULT 0, returned INT NOT NULL DEFAULT 0,
 UNIQUE(order_id,line_no), UNIQUE(order_id,product_id), FOREIGN KEY(order_id) REFERENCES purchase_orders(id), FOREIGN KEY(product_id) REFERENCES products(id),
 CHECK(quantity > 0 AND shipped >= 0 AND shipped <= quantity AND returned >= 0 AND returned <= shipped)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS shipments (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, order_id BIGINT NOT NULL, actor_id BIGINT NOT NULL,
 occurred_on DATE NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, note VARCHAR(1000) NOT NULL,
 FOREIGN KEY(order_id) REFERENCES purchase_orders(id), FOREIGN KEY(actor_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS shipment_lines (
 shipment_id BIGINT NOT NULL, line_id BIGINT NOT NULL, quantity INT NOT NULL,
 PRIMARY KEY(shipment_id,line_id), FOREIGN KEY(shipment_id) REFERENCES shipments(id), FOREIGN KEY(line_id) REFERENCES order_lines(id), CHECK(quantity > 0)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS suppliers (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL UNIQUE,
 contact VARCHAR(100) NOT NULL DEFAULT '', phone VARCHAR(40) NOT NULL DEFAULT '', address VARCHAR(300) NOT NULL DEFAULT '',
 active BOOLEAN NOT NULL DEFAULT TRUE, version INT NOT NULL DEFAULT 0
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS inventory_events (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, product_id BIGINT NOT NULL, actor_id BIGINT NOT NULL,
 kind VARCHAR(20) NOT NULL, delta INT NOT NULL, before_stock INT NOT NULL, after_stock INT NOT NULL,
 occurred_on DATE NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 note VARCHAR(1000) NOT NULL, supplier VARCHAR(100) NOT NULL DEFAULT '', supplier_id BIGINT NULL, order_id BIGINT NULL,
 CONSTRAINT fk_inventory_supplier FOREIGN KEY(supplier_id) REFERENCES suppliers(id),
 FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(actor_id) REFERENCES users(id), FOREIGN KEY(order_id) REFERENCES purchase_orders(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS order_returns (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, line_id BIGINT NOT NULL, quantity INT NOT NULL, restock BOOLEAN NOT NULL,
 reason VARCHAR(1000) NOT NULL, actor_id BIGINT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(line_id) REFERENCES order_lines(id), FOREIGN KEY(actor_id) REFERENCES users(id), CHECK(quantity < 0)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS action_requests (
 token VARCHAR(64) PRIMARY KEY, user_id BIGINT NOT NULL, action VARCHAR(40) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit_events (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, actor_id BIGINT NOT NULL, action VARCHAR(40) NOT NULL,
 target_id BIGINT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(actor_id) REFERENCES users(id)
) ENGINE=InnoDB;
